### ISSUE TITLE
localPrintString Offset ~= localTimeZone offset

### ISSUE THREAD

**Issue by seandenigris** [svenvc/ztimestamp#11]
Don't we make the same mistake in `#localPrintString` as DateAndTime, namely by using the current local offset instead of the (possibly historical) local offset of aZTimestamp? 

I assume you're familiar with this issue, but I described it more in depth [here](https://github.com/seandenigris/pharo/wiki/Room-for-Improvement-(i.e.-issues-problems)#time-zone-fiasco) and [here](https://github.com/ba-st/Chalten/issues/8#issue-550990548) if it helps.

I can't think of a great way to solve this because IIUC there is not a VM primitive to get the timezone in an abstract way (e.g. ID). 

### Possible solutions
* At minimum, a method comment with the limitation might be helpful
* Is there a reliable cross-platform way to get the timezone ID or similar? Maybe a new primitive is in order. This would pave the way to fix the core system and all libraries.
* Could the local timezone be optionally set/cached by ZT for the image? That of course would not cover every case, but at least it would give people the option
* Maybe this method should simply be removed since there's no easy and reliable way to implement it.

**Comment by svenvc** [comment]
Hi Sean,

You are absolutely right: this is confusing and actually wrong.

Since there is no (2) primitive, I will go for (3) for now and do (4) as well.

Sven

**Comment by svenvc** [comment]
Hi,

I forgot that there is a ZCurrentTimezone dynamic variable and the option #useCurrentTime to ZTimestampFormat. I integrated with that as well.

Here are the changes:

https://github.com/svenvc/ztimestamp/commit/f814ba6bcfc09bc4af8dac712e347a6612d7eefe

Sven
