### ISSUE TITLE
SubscriptOutOfBounds exception: (ZTimezone id: 'Etc/UTC') offsetForTimestamp: DateAndTime now. 

### ISSUE THREAD

**Issue by jvdsandt** [svenvc/ztimestamp#12]
This expression gives an error:

(ZTimezone id: 'Etc/UTC') offsetForTimestamp: DateAndTime now. 

Because a UTC timezone has zero transmissions. I get this error when reading TIMESTAMP WITHOUT TIME ZONE columns using P3Client from a database with UTC as the server timezone.

**Comment by svenvc** [comment]
Hmm, works for me:

(ZTimezone id: 'Etc/UTC') offsetForTimestamp: DateAndTime now.
 "0:00:00:00"
(ZTimezone id: #UTC) offsetForTimestamp: DateAndTime now.
 "0:00:00:00"

BTW, in the second case, a virtual, manually constructed ZTimezone object is used.

Are you sure you are using the latest version of ZTimestamp ? There were some recent changes.

**Comment by jvdsandt** [comment]
Oops, you are right. I was using an outdated version. Thanks!
