### ISSUE TITLE
Add documentation about defaultZoneInfoLocation

### ISSUE THREAD

**Issue by jecisc** [svenvc/ztimestamp#8]
I am trying to use a project depending on ZTimestamp on windows and I get an error saying that I need to initialize the info location of ZTimeZone myself via #zoneInfoLocation:. 

I don't know much about location management on the OSs so I don't really know what I should set. Maybe the comments/error could explain a little to users what they should do or give a link to a Wikipedia explanation.

**Comment by svenvc** [comment]
Hi Cyril,

Like the comment implies: you need the contents of the /usr/share/zoneinfo/ directory from a unix machine, so copy that over and point to it on Windows.

Unix machines keep updating this directory when timezones change (going forward).

Sven

**Comment by jecisc** [comment]
I don't have a Unix machine now and it seems hard to find a downloadable version :( 

Maybe we could have a copy in this project? But if it's often updated I understand it can be a real bother.

**Comment by svenvc** [comment]
Yeah, it is annoying, I will try to find a reasonable solution

**Comment by svenvc** [comment]
Commit d9aadbcdc4e117e3f28618fbe9ec69379f3a367c should offer a solution

The behaviour now is that if /usr/share/zoneinfo does not exist, a fallback copy is downloaded and that is used (although this is not ideal since this is a living DB that changes (is added to) each year.

Could you please test this on Windows ?

**Comment by jecisc** [comment]
Tests are green and I can use the project I wanted and that has ZTimestamp as dependency :)

**Comment by jecisc** [comment]
Thank you a lot for the fast fix!
